name: cloud_firestore_example
description: Demonstrates how to use the firestore plugin.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0+1

dev_dependencies:
  pedantic: ^1.8.0
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  